### ISSUE TITLE
1.0.8+ appears to break chffr

### ISSUE THREAD

**Issue by energee** [commaai/panda#103]
It looks like when we flash 1.0.8+ manually, it breaks wifi. It results in panda-xxxxx-BROKEN-pair SSID which blocks chffr pairing and probably wifi connections. Latest packaged release is OK.

**Comment by adamurban** [comment]
This appears to be due to this commit to enable compiler optimization:

https://github.com/commaai/panda/commit/786a004af51e1e54713a03f5c311b63a3703d48c

Setting the CFLAGS back to -O0 allows for a successful flash and a non-broken SSID, and also allows cffr to function again...
