### ISSUE TITLE
can2 on usb using can utils on Linux not working

### ISSUE THREAD

**Issue by Vansibel** [commaai/panda#143]
Can access data using wifi on can2. can0 and can1 work correctly using usb cable with can utils, but can2 does not work.
To reproduce: send can data to can2, connect usb cable then in terminal:
sudo ip link set can2 up
candump can2

**Comment by uincore** [comment]
https://github.com/uincore/panda/commit/4a893f2a8ac6aee39a9e9772f0d33465fb66861c
