### ISSUE TITLE
Cannot Receive messages from CAN bus as Device ID is not identified

### ISSUE THREAD

**Issue by MaheshKrishnaa** [commaai/panda#1479]
Hello ,

As part of a university project I am using the White Panda .
Im running the panda in a Linux machine (Ubuntu 20.04)

When i try to receive messages from the CAN bus i have a few errors relating to the device not being identified.
I have set up the udev rules as specified in the README file. 
![Screenshot from 2023-06-21 17-38-54](https://github.com/commaai/panda/assets/80395968/59ea9794-b47e-46db-ae85-7d195551abb8)
![Screenshot from 2023-06-21 17-38-59](https://github.com/commaai/panda/assets/80395968/86cc0fcf-4dde-4ef6-8a37-c9356b76cff2)

Im guessing it traces back to the Panda hardware not being identified.
Help regarding this would be greatly appreciated !

Best Regards 
Mahesh

**Comment by adeebshihadeh** [comment]
Our issue tracker isn't for software support. You can try the community discord at discord.comma.ai.
