### ISSUE TITLE
add more MISRA mutation test cases

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/panda#1770]
See https://github.com/commaai/panda/blob/master/tests/misra/test_mutation.py

**Comment by adeebshihadeh** [comment]
$100 for testing all board/safety/* files 
$250 for adding coverage to 10+ new MISRA rules  (just need to add patterns that violate each rule)

With the new cases, the mutation stage can't significantly slow down and must finish in 2mins.

**Comment by jimbrend** [comment]
where do I get all all board/safety/* files?
