### ISSUE TITLE
validate_checksum function improvement

### ISSUE THREAD

**Issue by MarinkoMagla** [commaai/panda#1903]
This function is under “TODO” inside panda/board/drivers/spi.h file. The function verifies the integrity of a data block by XORing all its bytes with an initial checksum value, returning true if the result is zero, indicating no corruption. The improvement can be made by casting the bulk to uint32_t and xor-ing the bytes afterwards.

![validate_cheksum](https://github.com/commaai/panda/assets/159032106/3e358127-d855-4040-b626-03a615e30d8d)

**Comment by adeebshihadeh** [comment]
ChatGPT?

**Comment by MarinkoMagla** [comment]
It is a snip and a comment from the file from this repo.
