### ISSUE TITLE
Updating libpanda test to use clang fails compilation

### ISSUE THREAD

**Issue by andiradulescu** [commaai/panda#1957]
Updating libpanda test to use clang (for macOS) https://github.com/andiradulescu/panda/commit/1e5d846d17dd32d1927638a60d73e96556f6539c fails compilation with:

```
In file included from panda/board/safety.h:12:
panda/board/safety/safety_chrysler.h:79:19: fatal error: initializer element is not a compile-time constant
  {CHRYSLER_ADDRS.CRUISE_BUTTONS, 0, 3},
   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
1 error generated.
```
Apple clang version 15.0.0 on latest macOS Sonoma 14.5.

**Comment by andiradulescu** [comment]
https://github.com/commaai/panda/pull/1958

**Comment by adeebshihadeh** [comment]
I think it's fine to keep this GCC since we use a GCC to build the actual FW.
