### ISSUE TITLE
Single-wire GMLAN support

### ISSUE THREAD

**Issue by vntarasov** [commaai/panda#2]
I don't have access to create a pull request.

What the attached diff does:
-  Fixes off-by-one error in can bus speed calculation, that was preventing single-wire GMLAN from working on my Chevy Volt gen 2.
- Makes it easier to understand, debug, and change the can speed configuration code.
- Enables sending/receiving extended addresses (majority of messages on single-wire GMLAN on my car).

[panda.patch.txt](https://github.com/commaai/panda/files/982669/panda.patch.txt)

**Comment by geohot** [comment]
Hmm, what do you mean you don't have access? It should be public. Can you screenshot the page showing no access?

**Comment by geohot** [comment]
Oh not sure what you were trying, but I don't see a panda repo in your account.

In order to do a pull request, first fork the repo to your account. Then push your changes to the fork. Then click pull request. It should work.

**Comment by vntarasov** [comment]
Yep, fork is what I missed. I talked to @edsammy earlier and he helped me realize that since I don't have push rights, I shouldn't try creating branches in the Panda repo directly, but fork it first, and create pull request from there. Will do that now.
