### ISSUE TITLE
How we use Panda to port a car?

### ISSUE THREAD

**Issue by adam-nelson** [commaai/panda#20]
As per title

**Comment by edsammy** [comment]
Check out this medium article about [panda + cabana](https://medium.com/@comma_ai/a-panda-and-a-cabana-how-to-get-started-car-hacking-with-comma-ai-b5e46fae8646) 

Also here you can find George doing a [live demo](https://www.pscp.tv/w/1jMKgokgOOMKL) of hacking on our new Toyota Prius
