### ISSUE TITLE
Legacy board doesn't work from devel branch

### ISSUE THREAD

**Issue by vntarasov** [commaai/panda#26]
Legacy board doesn't work from devel branch.

Repro:
As soon as boardd from openpilot/devel tries to use legacy board with legacy build firmware from panda/devel, red LED gets stuck in either on or off state. No CAN messages go in or out.

This is blocking me from developing safety changes for Volt.

**Comment by geohot** [comment]
panda devel branch isn't used. After we get https://github.com/commaai/panda/pull/23 in to master, devel will be reset to master.

**Comment by geohot** [comment]
Ok, should be good to build on master. safety is now nicely abstracted.
