### ISSUE TITLE
Does panda debug board  has no corresponding chip?

### ISSUE THREAD

**Issue by gucasbrg** [commaai/panda#265]
Could you help me see the process of panda,  Do I understand it right?

1. panda device has two hardware, one is STM32, one is ESP8266
2. panda inside op, board corresponding to STM32, boardesp corresponds to ESP8266, and then compile accordingly into panda device

I don't know if I understand it right,
In addition:  Someone told me panda debug board, it’s just hardware, no software- panda inside op, what is the reason?

**Comment by vangogh0318** [comment]
I also have the question about panda
