### ISSUE TITLE
kline_recv not working

### ISSUE THREAD

**Issue by quillford** [commaai/panda#28]
not sure if k line is fully implemented yet, but it just hangs when panda.kline_recv() is called. i'm communicating over wifi and panda.can_recv() works fine. panda is fully up to date according to ios chffr

**Comment by geohot** [comment]
It should work. Are you sending something on kline? Unlike CAN it blocks.

**Comment by quillford** [comment]
Not trying to send anything, just trying to read. I also tried over usb but the driver isn't working.

**Comment by edsammy** [comment]
@quillford is this still an issue for you?

**Comment by quillford** [comment]
not sure. one of the socket headers broke off when I was trying to remove my panda from the stocket, so I can't test until I fix that. the height on those headers seems odd, do you have a part number for it?

**Comment by edsammy** [comment]
Its these low profile ones from adafruit
https://www.adafruit.com/product/3008
