### ISSUE TITLE
Master branch not working with Windows 10 at all

### ISSUE THREAD

**Issue by fotiDim** [commaai/panda#297]
I tried the latest master branch and versions 1.0.1 and 1.0.7 and the current latest 1.5.1. All of them give "Device has malfunctioned and windows doesn't recognize it". I even tried replacing the drivers with Zadig to all available options but also not any luck there. I am on the latest Windows 10 update (1903).

The only thing that kind of worked for me was the `stable` branch. I was able to recognize the panda and to pull live data from Cabana. However I had no luck with Honda iHDS which refuses to connect to the vehicle.

**Comment by robbederks** [comment]
This should be fixed by jyoung8607's PR!
