### ISSUE TITLE
panda schematic

### ISSUE THREAD

**Issue by dlednik** [commaai/panda#400]
Is it possible to get the schematics for panda OBD-II?

**Comment by robbederks** [comment]
All hardware designs are closed-source, although you can find the pinout for the OBD-II connector here: https://medium.com/@comma_ai/a-panda-and-a-cabana-how-to-get-started-car-hacking-with-comma-ai-b5e46fae8646

**Comment by dzid26** [comment]
Hopefully reverse engineering is not frowned upon
![20191209_222148](https://user-images.githubusercontent.com/841061/71324149-64f3e580-24a9-11ea-8e1e-13dac6af5200.jpg)
![20191209_221058](https://user-images.githubusercontent.com/841061/71324154-6fae7a80-24a9-11ea-988c-9731b88fee44.jpg)
![20191209_211621](https://user-images.githubusercontent.com/841061/71324155-73420180-24a9-11ea-9e3b-d4f6470d0452.jpg)
![20191210_213228](https://user-images.githubusercontent.com/841061/71324172-a5536380-24a9-11ea-9017-8e8ebb4992d0.jpg)
![20191210_212756](https://user-images.githubusercontent.com/841061/71324173-a5536380-24a9-11ea-8dd6-b588c5067ce4.jpg)
![20191210_212914](https://user-images.githubusercontent.com/841061/71324174-a5536380-24a9-11ea-976d-6e12bbb16e62.jpg)
![20191209_211444](https://user-images.githubusercontent.com/841061/71324175-a5ebfa00-24a9-11ea-8bba-3c420a8deb49.jpg)

**Comment by dlednik** [comment]
@dzid26 was thinking in that direction but decided it might be better to make a new one based on ST32 that has arduino bootloader available :)

**Comment by dzid26** [comment]
Yeah, it depends on what you need it for. 

My story was that I just needed a single digital output, but I found no direct connections between the board and OBD pins. Then I figured GMLAN or LIN could work as digital out to some degree.  Later, luckily, I noticed Comma already implemented the digital outs using those pins.

**Comment by martiinezz** [comment]
Did you guys recognize all parts? I know can transceiver is NXP and LIN too. Looks rather simple. I was thinking about doing some proper diagnostics interface for cars but this form factor is too small IMHO.

**Comment by dlednik** [comment]
If you gonna build your own part# don't matter that much as you can use whatever you want :)

I did not had time yet to work on this. But if there is interest for an OS project we can collaborate. Need to finish a webstore for client first but after that I can dedicate more time for this.

**Comment by martiinezz** [comment]
I know - to be hones I don't even like that Panda is so small. Already recognized that most elements are build (including layout) to chips manufacturers recommendations. Should be quite easy to put it all together. I also noticed that there has been some changes compared to what is shown in leaflet that comes with Panda. For example current sensor and LDO for ARM is now on the other side than ESP. Also GM LAN moved so ST buck converter can easier dissipate heat thru vias.

**Comment by luannbrandao** [comment]
> @dzid26 was thinking in that direction but decided it might be better to make a new one based on ST32 that has arduino bootloader available :)

you did it?

**Comment by dlednik** [comment]
> > @dzid26 was thinking in that direction but decided it might be better to make a new one based on ST32 that has arduino bootloader available :)
> 
> you did it?

no, not enough interest and still busy with other stuff, but like I said open to start and collaborate on OS variant to tap into cars OBD2 data

**Comment by martiinezz** [comment]
I have identified all components here: https://github.com/martiinezz/panda/tree/master/white-hw - most other components are exactly the same as listed chip makers reference designs. Easy to reproduce. Winter is coming and I finally might start KiCad design

**Comment by dzid26** [comment]
>  Easy to reproduce. Winter is coming and I finally might start KiCad design

https://github.com/lukasloetkolben/OpenpilotHardware/tree/main/BlackPanda/kicad_project
Maybe black&white panda breed. ;)

**Comment by martiinezz** [comment]
I don't have black panda at hand so unable to reproduce :(
