### ISSUE TITLE
ISO26262: add checksum/counter checks for Hyundai

### ISSUE THREAD

**Issue by rbiasini** [commaai/panda#410]

**Comment by rbiasini** [comment]
Too many different ways of computing the checksum, depending on the car model (3 in master right now). Perhaps we should drop support for some legacy models with obsolete checksum logic.

**Comment by adeebshihadeh** [comment]
Counter checks done in #530

**Comment by adeebshihadeh** [comment]
Checksums done for all messages, except [wheel speeds](https://github.com/commaai/panda/blob/master/board/safety/safety_hyundai.h#L11)
