### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by tspannhw** [commaai/panda#46]
any additional examples for reading diagnostics on moving vehicle

**Comment by haukesand** [comment]
Did anybody ever use this with a Nissan?

**Comment by tspannhw** [comment]
I cannot get it to work with Toyota 4Runner 2014

**Comment by mayo** [comment]
@haukesand I’m using it on 2010 Xterra. There are no rbc files yet, but it’s work in progress.

**Comment by rbiasini** [comment]
`panda/examples` should provide enough use cases on how to use a Panda for vehicle diagnostic.
We now also have a UDS library in `panda/python/uds.py`
