### ISSUE TITLE
NEO compatibility broken

### ISSUE THREAD

**Issue by deanlee** [commaai/panda#537]
https://github.com/commaai/panda/blob/94c995f0a9ae420124060cb406b44814dd80c82d/board/board.h#L26-L29

I got many "TURN ON CHARGING" warning after applied this commit.failed to engage

**Comment by robbederks** [comment]
Hi, are you sure this commit broke the panda for you? 
To test, you could run the `tests/debug_console.py` after rebooting the panda, and see what type of board it reports. If you're using a Comma 2, it should report as `Board type: Uno`

**Comment by deanlee** [comment]
I am using the comma 1.previous generation device. 

> ************************ MAIN START ************************
Config:
  Board type: Black
  USB serial
  No bootmode
detected car harness with orientation 01
switching harness to passthrough (relay off)
setting CAN2 to be normal
switching harness to passthrough (relay off)
**** INTERRUPTS ON ****
ESUSP detected
USB reset
enumeration done
USB reset
enumeration done
USB enumeration complete
EON hasn't sent a heartbeat for 0x00000002 seconds. Safety is set to SILENT mode.
enable power savings
EON hasn't sent a heartbeat for 0x00000003 seconds. Safety is set to SILENT mode.
EON hasn't sent a heartbeat for 0x00000004 seconds. Safety is set to SILENT mode.
EON hasn't sent a heartbeat for 0x00000005 seconds. Safety is set to SILENT mode.
EON hasn't sent a heartbeat for 0x00000006 seconds. Safety is set to SILENT mode.
EON hasn't sent a heartbeat for 0x00000007 seconds. Safety is set to SILENT mode.
EON hasn't sent a heartbeat for 0x00000008 seconds. Safety is set to SILENT mode.
EON hasEON hasn't sent a heartbeat for 0x00000017 seconds. Safety is set to SILENT mode.

currently,I have ot comment out the if(!detect_with_pull(GPIOB, 1, PULL_UP)) statement to make it work again.

**Comment by pd0wm** [comment]
@deanlee you mean a NEO board? https://github.com/commaai/neo

**Comment by deanlee** [comment]
yes

**Comment by robbederks** [comment]
Oh, I see. This was only tested on the new(er) generation pandas (white, grey, black, uno, ...), not on the NEO board. That board has been deprecated a very long time ago, actually surprised it still worked at all.
I see two solutions:
- Run a fork which maintains compatibility for the NEO
- Make a PR with another board for NEO, and figure out a way to detect this. If this is clean and doesn't break any functionality, I think we should be able to merge that
