### ISSUE TITLE
USB OTEPDIS interrupt Error

### ISSUE THREAD

**Issue by xx979xx** [commaai/panda#546]
**when trying debug_console.py, I and others are getting this error continuously:
`OUTEP3 error 00000010`**
<img width="1366" alt="2020-05-26_10 43 50" src="https://user-images.githubusercontent.com/40252818/83216120-2f96a680-a171-11ea-8b66-87f13e58f114.png">

it is generated from [board/drivers/usb.h line 836](https://github.com/commaai/panda/blob/a618e64d1a1778f5b3ac95dcd8a41b64d1a18a3f/board/drivers/usb.h#L836) after receiving `USB_OTG_DOEPINT_OTEPDIS` interrupt which received when "OUT token received when endpoint disabled".
the stm32f413 reference manual page 1220 added that: it 

> Applies only to control OUT endpoints.
> Indicates that an OUT token was received when the endpoint was not yet enabled. This
> interrupt is asserted on the endpoint for which the OUT token was received.

I am not sure if this a bug or happens by design so I can remove it from being printed as an error

**Comment by robbederks** [comment]
Not sure why this triggers, have not seen this myself yet.
Do you have an easy way to reproduce?

**Comment by xx979xx** [comment]
> Not sure why this triggers, have not seen this myself yet.
> Do you have an easy way to reproduce?
you can use `HKG_community` fork from [here](https://github.com/xx979xx/openpilot) as well as '7.6-dev`

**Comment by robbederks** [comment]
@gregjhogan this is the same issue you reported it seems like? Will look into it

**Comment by gregjhogan** [comment]
@robbederks looks the same, but when I encountered the issue all TX would stop
