### ISSUE TITLE
Allow more Granular CAN Forwarding

### ISSUE THREAD

**Issue by energee** [commaai/panda#57]
Although there is forwarding for a full bus, there is no simple way to mask CAN ids so that _partial_ messages are forwarded / removed. Would you consider adding files similar to safety_*.h that could be referenced by openpilot for modifying CAN traffic safely with the panda?

It looks like so far, this is required for the Tesla port and Honda CR-V/Hatchback port and would be required for preserving some OEM Toyota and Honda features like automatic lights.

**Comment by gregjhogan** [comment]
#90 added support for message level forwarding in safety modes
