### ISSUE TITLE
Docker build fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by StealthBadger747** [commaai/panda#600]
It seems to fail on the last step.

`Step 19/20 : RUN cd /tmp && git clone https://github.com/commaai/panda_jungle.git
 ---> Running in f9ce2491caed
Cloning into 'panda_jungle'...
Removing intermediate container f9ce2491caed
 ---> ae1a2061d07e
Step 20/20 : ADD ./panda.tar.gz /tmp/panda
ADD failed: stat /var/lib/docker/tmp/docker-builder908973756/panda.tar.gz: no such file or directory`

**Comment by adeebshihadeh** [comment]
panda.tar.gz is missing. It's just a git archive of the panda repo. You can generate it with: `git archive -v -o panda.tar.gz --format=tar.gz HEAD`
