### ISSUE TITLE
Wifi update fail

### ISSUE THREAD

**Issue by kahvis** [commaai/panda#601]
Hi,

ssid: panda-00d11d21-BROKEN

st version:     
esp version:    v1.1.1-9cffa74e-RELEASE
esp flash file: user2.bin
in INSECURE mode...secure it

Did I lock my self out to update and fix wifi? I can of course get my password with examples/get_panda_password.py
The problem is here that panda-*-BROKEN password is not the same if I secure the connection.

board/make recover - works
python/flash_release.py - works, but is not doing anything with wifi binaries

**Comment by robbederks** [comment]
Wifi on the white pandas has been deprecated (#592 ). If you still want to use it, you'll have to go back to an old commit
