### ISSUE TITLE
panda blinking with red LED

### ISSUE THREAD

**Issue by stplaydog** [commaai/panda#607]
When I connected my panda with panda paw, I can only see red LED blinking, and 
```
sudo dfu-util -l 
```
does not show anything. Is there anyone who can help me?

**Comment by vanillagorillaa** [comment]
Sounds like you aren't putting it into DFU mode properly. With the paw connected to the panda on one end, and the usb cable connected to your computer, flip the power switch to off on the paw, hold the DFU button, flip the power switch on, release the DFU button. If done properly the panda should have no LED. 

For more help please use our community discord, discord.comma.ai.
