### ISSUE TITLE
Pedal firmware broken unless USB Flag enabled

### ISSUE THREAD

**Issue by vanillagorillaa** [commaai/panda#613]
After weeks of debugging, and a hint from @robbederks, it appears that the pedal firmware is broken unless enabling the usb flag in main. 

If flashing the latest build without the flag the car faults and it appears that the pedal never turns on when given 5v (going off of the LED indicator). If the flag is enabled it is fine. 

I tested with another good, known working pedal which is on an older, unknown version (probably somewhere around the 0.6.3 openpilot update which required a new pedal firmware) and this worked. It appears that on this other pedal the USB flag is disabled as I am unable to see it's connection to my linux machine.  

I have yet to go back commit by commit to find a working one without this flag enabled but plan to do so now that I know I have a working setup.

**Comment by cydia2020** [comment]
this does seem to be the case, I've initially flashed with all my pedals with the stock firmware, but none of them worked. After asking around on discord and enabling the usb flag, everything seemed to be normal.
