### ISSUE TITLE
IR LEDs constantly on with GM

### ISSUE THREAD

**Issue by VirtuallyChris** [commaai/panda#621]
Volt people have a different ignition detection that detects CAN messages on the bus instead of detecting a rise in the ignition line. Due to this, the IR LEDs never turn off. (at least is what it seems like!) Confirmed with several GM users on Discord that this happens to them, and they're forced to unplug their devices after each drive.
![image](https://user-images.githubusercontent.com/37757984/105425565-76ed0e00-5bfe-11eb-93ee-c30bf1ae2041.png)

**Comment by robbederks** [comment]
I briefly looked into this a few weeks ago, and none of the logic about when to turn the IR LEDs on/off is in the panda (except for the heartbeat being missing turning them off).
Also looked into the openpilot side, but there the remainder of the code seems to be shared between both ignition types when the health packet comes in. 
Requires more investigation!

**Comment by dibble9012** [comment]
Happens to me
Device Dongle ID: 970dccbaef8569a7
2017 Chevy Volt

**Comment by ErikRNissen** [comment]
I’m seeing this on a2018 volt as well.   Any time I check the interior cam the ir LEDs appear to be on 
![BF448826-0861-4095-8245-7A8E8CAE4454](https://user-images.githubusercontent.com/67850528/106221200-ff852480-6191-11eb-836e-8e87a5f6396b.png)

**Comment by Verylukyguy** [comment]
Happens to me.

Dongle ID:  e38a02cae1ef1e0c

2018 GMC Acadia Denali AWD

**Comment by jeffpicard** [comment]
+1 
Dongle ID: 9b7062f1d55b8e78
2017 Chevy Volt

My comma2 shuts off if i haven't driven the car for around 2 days. Ditto ErikRNissen -- my interior cam always shows the IR lights on.

**Comment by robbederks** [comment]
Thanks for the reports, we're going to look into this issue further.

As far as the IR being on while taking a snapshot, that's completely expected behavior and not indicative of any issues.
The problem this issue is about is the IR being on while the device is offroad / idle. When taking a snapshot, the IR LEDs turn on for a brief duration.

**Comment by robbederks** [comment]
Dug a little deeper and found the issue. The issue is indeed related to the panda code.

The IR PWM controller uses timer 4 (TIM4), which apparently is also used by the GMLAN bitbanging driver.
Will move the GMLAN bitbanging to a different timer to fix this issue. PR coming soon!

**Comment by dibble9012** [comment]
Awesome!!! Now I don’t have to worry about a dead battery after three days. Thank you!
