### ISSUE TITLE
Can_logger.py - how to get data like speed, distance from CAN Bus

### ISSUE THREAD

**Issue by soneji** [commaai/panda#646]
Hi

I’m not sure if this is the best place to ask this but I have a comma 2 and I was wondering if it is possible to write my own python scripts using panda on the comma itself, to feed the data from the comma/panda to another system. 

I have tried using can_logger.py but I would love if someone could point me in the right direction of whether this is the right tool, and what the output data from the can logger actually is/what format/how can I use it. 

I would ideally like to get the speed at which the car is going and experiment with any other metrics I can get from the car. 

Thank you all in advance and thanks for working on such an incredible open source project to revolutionise the way the automotive industry takes on the new technological era of driver assistance.  

<details>
<summary>PS</summary>
Also if this is the wrong place for this, let me know and I’ll close this and take the question there 😅 
</details>

**Comment by robbederks** [comment]
This is definitely possible, although you'd need to parse out the needed data from the raw CAN messages. These definitions are usually encoded in a DBC file, see https://github.com/commaai/opendbc for examples.
