### ISSUE TITLE
No dataset using panda

### ISSUE THREAD

**Issue by abylikhsanov** [commaai/panda#67]
Hello,

I have purchased panda and tried to gather information about my car (VW polo 2016) but when I logged into cabana, it couldn't read any data. It said that I need to reverse engineer.

**Comment by quarksteilchen** [comment]
Hi. Currently have a similar issue.
@abylikhsanov : How are the LEDs blinking?

For me, Panda+chffr only blink red+steady wifi-blue. - When used with the Torque-Android app, Panda blinks much more. - Have you tried that already?
