### ISSUE TITLE
UI interface report "CAN Error: Check Connections"

### ISSUE THREAD

**Issue by LIHaoran-good** [commaai/panda#685]
I use the webcam tool to run openpilot on PC and Vehicle . We refer to the [guideline](https://github.com/commaai/openpilot/tree/master/tools/webcam) .When input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py", UI interface displays error " CAN Error: Check Connections  " ,
and manager.py output: "selfdrive/boardd/panda.cc: Transmit buffer full" 
How to solve it ? Thanks.

**Comment by adeebshihadeh** [comment]
This is in openpilot, not panda. Check out https://discord.comma.ai for help getting started.
