### ISSUE TITLE
Angle control safety: make sure requested angle is close to current angle

### ISSUE THREAD

**Issue by robbederks** [commaai/panda#771]

**Comment by adeebshihadeh** [comment]
@sshane this still an issue?

**Comment by sshane** [comment]
@robbederks what was the thinking on this? Was this to limit torque when overriding? For Nissan, we can directly control max torque, for Toyota we wind down steering on steer pressed, and with Ford, it has logic to limit angle near desired for overriding.

**Comment by robbederks** [comment]
Can't remember what the thought process behind this was. I know the EPS will fault on Tesla if you request an angle too far away (effectively rate limiting it), but we already do this iirc.

Unless something else pops in mind, I think we can close this

**Comment by sshane** [comment]
Sounds like this should be some fault avoidance code in openpilot if that is the issue
