### ISSUE TITLE
Specs in README.md outdated?

### ISSUE THREAD

**Issue by kq01526** [commaai/panda#78]
Hi,

the README.md says:

>    ELM327 (planned)
>    Windows J2534 (planned)

The online shop says:

> Wi-Fi ELM327 (Android and iOS apps)
> Windows J2534 (Car manufacturer tools)

Which one is correct?

**Comment by energee** [comment]
The latter, however J2534 is still alpha.

**Comment by geohot** [comment]
Fixed
