### ISSUE TITLE
Block actuation while in the pre-enable state

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/panda#843]
Currently, only the Honda safety handles this.

**Comment by adeebshihadeh** [comment]
@sshane is this done?

**Comment by sshane** [comment]
I believe the topic of this PR was to enforce pre-enable safety when enabling with gas pressed, however we now allow steering in pre-enable state and longitudinal pre-enabling is done with the common checks in safety.h. Relevant PRs: https://github.com/commaai/panda/pull/884 and https://github.com/commaai/panda/pull/1121

We still need to block actuation when pre-enabling at a stop in is this draft PR which I'm trying to clean up: https://github.com/commaai/panda/pull/1123
