### ISSUE TITLE
Sleep in _recv_dto

### ISSUE THREAD

**Issue by danielkucera** [commaai/panda#867]
Hello,
I just want to ask if this sleep is not counter-productive, isn't `self._panda.can_recv()` blocking?
https://github.com/commaai/panda/blob/51ccb9fbd266796e1bf6ffda8b93c4119ab09ff4/python/ccp.py#L132

https://github.com/commaai/panda/blob/51ccb9fbd266796e1bf6ffda8b93c4119ab09ff4/python/ccp.py#L100

**Comment by adeebshihadeh** [comment]
No, `can_recv` isn't blocking.
