### ISSUE TITLE
Need GMLAN and CAN2 at the same time

### ISSUE THREAD

**Issue by linagee** [commaai/panda#9]
Assuming there is something interesting on GMLAN (aka: Low speed GMLAN / aka: Low speed CAN / 33kbit/sec), I need CAN2 and GMLAN to work at the same time. (In response to the PDF saying that they both cannot be used at the same time.)

CAN2 = "Object High Speed GMLAN" on my Chevy Volt gen2 w/front radar. (They call everything a GMLAN, just high speed / low speed.)

I'm not sure if there is something interesting on GMLAN (pin 1), I'll know in a week or two, but this seems like a bit of a mistake on the Panda of not knowing that both would be needed at the same time.

Also, is there a way to hook up to OBD2 pin 1 (GMLAN) on the Neo? (GMLAN / Low speed CAN, non-differential.) I see that a differential CAN driver is used there, is there a schematic for the Panda to know how this hooks in? (Panda feels a bit half-open sourced unless I'm just not finding the repo? And the secret wifi key?) Can I just use one of the differential drivers to talk non-differential CAN?

Also, if I get a Panda one day (I'm up to over a thousand comma points so I hope soon? Not sure if its all time high or weekly high?), how is the CAN data used? Do I have open access to all of that? Are the values for knowing steering already known for GM? Will this turn into a decentralized attempt to de-obscure all PIDs on all makes/models of vehicles, or is it just something Comma can see?

**Comment by geohot** [comment]
You have access to all your CAN data if you click the purple checkmark. I know the interface is bad... We have a really cool launch planned soon. You also have access to CAN data if you are using a NEO, not just a Panda.

And absolutely the reversing effort will be open, see https://github.com/commaai/opendbc for a start. comma.ai wins if cars are more open period, no reason to lock it down. We are building tools to make it really easy!

Rev C panda will support GMLAN multiplexed with CAN2 or CAN3, but all current Panda are still Rev B and only with CAN2.

Panda software is bazaar style 100% open source, hardware is not. If you want to develop and would like a free Panda, e-mail george@comma.ai with a development plan. If it's good, we'll send you one.
