### ISSUE TITLE
How to compile panda

### ISSUE THREAD

**Issue by ufc12345** [commaai/panda#911]
I want to compile the panda I bought with the source files you shared, but I can't. I keep getting compile error because of file and library distribution. How do I compile the file you shared on stm32 inside panda? I bought the product but I cannot use it the way I want.

![1](https://user-images.githubusercontent.com/100275337/161970105-6c348068-7701-4442-ae56-139174a43c66.jpg)
![2](https://user-images.githubusercontent.com/100275337/161970115-447f6685-456f-4bbc-8426-0738475f3068.jpg)

**Comment by robbederks** [comment]
Have you tried the `flash.sh` script in the `board/` folder? There's some instructions in that `README.md` file too.
