### ISSUE TITLE
add support for CAN-FD 1.0

### ISSUE THREAD

**Issue by gregjhogan** [commaai/panda#916]
currently we only support CAN-FD 2.0 (which is the ISO standard) but the red panda can support CAN-FD 1.0 which is used by Hyundai Palisade blind spot radars.

enabled by setting NISO bit in FDCAN_CCCR register (see https://github.com/gregjhogan/panda/commit/f801919dd858a0935e502f2ce7a4c0585f2e4478)

**Comment by adeebshihadeh** [comment]
If you're in a non-car safety mode, I think it's fine to switch between ISO and non-ISO CAN FD until valid messages are seen.
