### ISSUE TITLE
Where can I buy panda?

### ISSUE THREAD

**Issue by incarry** [commaai/panda#922]
hello guys,
After reading you're [blog](https://blog.willemmelching.nl/carhacking/2022/01/02/vw-part1/), I want to buy a panda,

- [ ] where can I buy it? 

- [ ] Or I buy an STM32 to make panda, how does it program download?

thanks! :)

**Comment by incognitojam** [comment]
You can buy different panda variants on the shop :) https://comma.ai/shop/products/panda
