### ISSUE TITLE
safety: add flags for assumed mutually exclusive msgs

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/panda#924]
In many safety modes, we check two addresses assuming that they are mutually exclusive, but this isn't guaranteed to be the case.

**Comment by adeebshihadeh** [comment]
@sshane how are we doing on this? I believe these were all leading to controls mismatches, so should probably be fixed.

**Comment by sshane** [comment]
Do you have any examples?

**Comment by adeebshihadeh** [comment]
Recent RX refactor plus the fuzzing tests will take care of this.
