### ISSUE TITLE
Rust implementation

### ISSUE THREAD

**Issue by jwinarske** [commaai/panda#960]
Any interest in a Rust implementation of the Panda firmware?  It would be feature parity to the C implementation, safer, and most likely a smaller image.

**Comment by geohot** [comment]
Copied from openpilot.

Again, why do this? A new codebase would have a new set of bugs. I also see very few places where the C code is holding us back. While these things would be fun projects, we are a company with a mission, and supporting the migration of the panda firmware to Rust is not where we should be spending our time.

If you'd like to contribute to panda, bugfixes are the most welcome, followed by small readable and tested refactors that either improve performance or readability. More comprehensive testing would also be welcome.
